language: python
python: 2.7
env:
  - TOX_ENV=pypy-trunk
  - TOX_ENV=pypy-1.6.X
  - TOX_ENV=pypy-1.5.X
  - TOX_ENV=pypy-1.4.X
  - TOX_ENV=py27-trunk
  - TOX_ENV=py27-1.6.X
  - TOX_ENV=py27-1.5.X
  - TOX_ENV=py27-1.4.X
  - TOX_ENV=py26-1.6.X
  - TOX_ENV=py26-1.5.X
  - TOX_ENV=py26-1.4.X
install:
  - pip install coveralls
  - pip install tox
script: tox -e $TOX_ENV
after_success: coveralls
