language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

install:
  - pip install coveralls
  - pip install -r requirements_dev.txt
script: coverage run run_tests.py
after_success: coveralls
